// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjqfxabgnjkpdzprbvms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqcWZ4YWJnbmprcGR6cHJidm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MTAwMjYsImV4cCI6MjA3MTQ4NjAyNn0.2tjXw-vUKBCnxIQFe0F7MnPlXfa92fJynaVj6IHE-R8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});